# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36f9d8abb53f9bb76bad3fc887924131a0d20496e9d4cdcb21a048b23f073a805d4b0a1b1d6a0e1de464b0187aba4132a9cb40a7c29bf853afaccec19a0887f4

test:
  secret_key_base: 6b66186f0adc635ce1448150d929ce17852afe367a4d9addd55f1baf3afb8287d024d4efb943af011432b145593b46af491acd67adf1a51ae891ebd0a80e3263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
